# AutoSKU Sync Shopify App Configuration

[shopify]
api_key = "<YOUR_SHOPIFY_API_KEY>"
api_secret = "<YOUR_SHOPIFY_API_SECRET>"
scopes = ["read_products","write_products","read_inventory","write_inventory"]
embedded = true
host = "https://your-app-domain.com"
redirect_urls = ["https://your-app-domain.com/api/auth/callback","https://your-app-domain.com/api/auth/custom"]

[[shopify.webhooks]]
topic = "inventory_levels/update"
address = "https://your-app-domain.com/api/webhooks/inventory_update"
format = "json"

[[shopify.webhooks]]
topic = "products/create"
address = "https://your-app-domain.com/api/webhooks/product_create"
format = "json"

[[shopify.webhooks]]
topic = "products/update"
address = "https://your-app-domain.com/api/webhooks/product_update"
format = "json"

[billing]
plan_name = "AutoSKU Pro"
redirect_url = "https://your-app-domain.com/upgrade"

[billing.price]
amount = 19.99
currency = "USD"
interval = "month"

[google]
client_id = "<GOOGLE_CLIENT_ID>"
client_secret = "<GOOGLE_CLIENT_SECRET>"
redirect_uri = "https://your-app-domain.com/api/google/oauth2callback"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
scopes = ["https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/drive.file"]

[csv]
max_file_size_mb = 10
allowed_mime_types = ["text/csv","application/vnd.ms-excel"]

[database]
client = "postgresql"
host = "db.host"
port = 5432
user = "dbuser"
password = "dbpass"
database = "dbname"
ssl = true

[cors]
allowed_origins = ["https://your-app-domain.com"]
allowed_methods = ["GET","POST","PUT","DELETE","OPTIONS"]
allowed_headers = ["Content-Type","Authorization"]

[logging]
level = "info"
format = "json"
output = "stdout"

[app]
default_page = "/dashboard"
max_concurrent_syncs = 3
session_storage = { type = "memory" }